### PR TITLE
fix(gitlab): add support for gitlab subgroups

### PR DESCRIPTION
**Pull request by canercandan**
#7

### CODE REVIEW

**Comment by hutson** [comment]
:+1: Looks good to me.

**Comment by hutson** [comment]
:+1: Following on the most recent changes, I'm reaffirming that this change looks good.

**Comment by bahmutov** [comment]
First time TravisCI could not publish the new version
```
1.97s$ npm run semantic-release
> parse-github-repo-url@0.0.0-semantic-release semantic-release /home/travis/build/repo-utils/parse-github-repo-url
> semantic-release pre && npm publish && semantic-release post
npm ERR! publish Failed PUT 401
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.8.4/bin/node" "/home/travis/.nvm/versions/node/v4.8.4/bin/npm" "publish"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.12
npm ERR! code E401
npm ERR! You must be logged in to publish packages. : parse-github-repo-url
```

Seems the `NPM_TOKEN` has been disabled. I refreshed this and `GH_TOKEN` using `semantic-release-cli`, hope it solves the issue.

**Comment by bahmutov** [comment]
Yes, it did - published https://github.com/repo-utils/parse-github-repo-url/releases/tag/v1.4.1

**Pull request merged**
